# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(428, 233)
        LoginForm.setModal(True)
        self.formLayout_2 = QtWidgets.QFormLayout(LoginForm)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(LoginForm)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtUserID = QtWidgets.QPlainTextEdit(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtUserID.sizePolicy().hasHeightForWidth())
        self.txtUserID.setSizePolicy(sizePolicy)
        self.txtUserID.setMinimumSize(QtCore.QSize(0, 30))
        self.txtUserID.setMaximumSize(QtCore.QSize(16777215, 24))
        self.txtUserID.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtUserID.setTabChangesFocus(True)
        self.txtUserID.setObjectName("txtUserID")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtUserID)
        self.label_2 = QtWidgets.QLabel(LoginForm)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtAccessToken = QtWidgets.QPlainTextEdit(LoginForm)
        self.txtAccessToken.setMinimumSize(QtCore.QSize(0, 30))
        self.txtAccessToken.setTabChangesFocus(True)
        self.txtAccessToken.setObjectName("txtAccessToken")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtAccessToken)
        self.buttonBox = QtWidgets.QDialogButtonBox(LoginForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.label_3 = QtWidgets.QLabel(LoginForm)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtHomeserver = QtWidgets.QPlainTextEdit(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHomeserver.sizePolicy().hasHeightForWidth())
        self.txtHomeserver.setSizePolicy(sizePolicy)
        self.txtHomeserver.setMinimumSize(QtCore.QSize(0, 30))
        self.txtHomeserver.setMaximumSize(QtCore.QSize(16777215, 24))
        self.txtHomeserver.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtHomeserver.setTabChangesFocus(True)
        self.txtHomeserver.setObjectName("txtHomeserver")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtHomeserver)
        self.chkSave = QtWidgets.QCheckBox(LoginForm)
        self.chkSave.setObjectName("chkSave")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.chkSave)

        self.retranslateUi(LoginForm)
        self.buttonBox.accepted.connect(LoginForm.accept) # type: ignore
        self.buttonBox.rejected.connect(LoginForm.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginForm)
        LoginForm.setTabOrder(self.txtHomeserver, self.txtUserID)
        LoginForm.setTabOrder(self.txtUserID, self.txtAccessToken)
        LoginForm.setTabOrder(self.txtAccessToken, self.chkSave)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Matrix Login"))
        self.label.setText(_translate("LoginForm", "User ID:"))
        self.txtUserID.setPlaceholderText(_translate("LoginForm", "@somanyfoxes:foxesarecute.local"))
        self.label_2.setText(_translate("LoginForm", "Access Token:"))
        self.txtAccessToken.setPlaceholderText(_translate("LoginForm", "Access Token goes here"))
        self.label_3.setText(_translate("LoginForm", "Homeserver:"))
        self.txtHomeserver.setPlainText(_translate("LoginForm", "https://matrix-client.matrix.org"))
        self.txtHomeserver.setPlaceholderText(_translate("LoginForm", "https://matrix-client.matrix.org"))
        self.chkSave.setText(_translate("LoginForm", "Remember (insecure)"))
